apiVersion: v1
kind: Service
metadata:
  name: www
spec:
  ports:
    - name: http-test1
      port: 80
      protocol: TCP
      # nodePort: 8080
    - name: database
      port: 3306
      protocol: TCP
      # nodePort: 8081
  type: NodePort
  selector:
    app: www